name: Check Cruft Update with conflicts

on:
  push:
    paths:
      - '**/.cruft.json'

jobs:
  update:
    runs-on: [ "{{cookiecutter.github_runner_scale_set_name}}" ]

    steps:
      - uses: actions/checkout@v4

      - name: Check for .rej files
        run: |
          if find . -name "*.rej"; then
              echo "Error: Found .rej files indicating merge conflicts. Please resolve these conflicts manually."
              exit 1
          fi

      - name: Check for conflict markers
        run: |
          conflict_files=$(grep -rlE '<<<<<<<|=======|>>>>>>>' . --exclude-dir=.github) || true
          if [[ ! -z "$conflict_files" ]]; then
            echo "Error: Found files with conflict markers:"
            echo "$conflict_files"
            echo "Please resolve these conflicts manually."
            exit 1
          else
            echo "No conflict markers found."
          fi
